### ISSUE TITLE
there is no such file: IMC0.mat

### ISSUE THREAD

**Issue by zhushuzhao** [YoungBigBird1985/GCN-MF#1]
In util.py--load_IMC_data(fold=0)>>features=sio.loadmat('data/'+'IMC'+str(fold)+'mat'). But there is no such file about IMC

**Comment by YoungBigBird1985** [comment]
Hi,

The data file is too large to be uploaded to github. If you have any online
server or ftp, I can send the files to you.

**Comment by XiejcSYSU** [comment]
Also want IMC file, and thank you for your contribution!

**Comment by YoungBigBird1985** [comment]
Could you provide a cloud disk, where I can upload the file "IMC"?

**Comment by zhushuzhao** [comment]
https://www.dropbox.com/request/Qu1UM2I45sFIMJ94WFys
I initiated a file request, thanks!

**Comment by YoungBigBird1985** [comment]
Thanks, and I will attach the link to my homepage.

**Comment by zhushuzhao** [comment]
The input data file sharing link:  https://www.dropbox.com/sh/2uwqlfpqh2tdzi6/AAADqgTrn8pAxJ9PYH2shT9ja?dl=0

**Comment by wangxiaosong96** [comment]
models.py---------'NIMC_MF' object has no attribute 'update_history'    Why report an error？

**Comment by wangxiaosong96** [comment]
> 输入数据文件分享链接：[https](https://www.dropbox.com/sh/2uwqlfpqh2tdzi6/AAADqgTrn8pAxJ9PYH2shT9ja?dl=0) : [//www.dropbox.com/sh/2uwqlfpqh2tdzi6/AAADqgTrn8pAxJ9PYH2shT9ja?dl=0](https://www.dropbox.com/sh/2uwqlfpqh2tdzi6/AAADqgTrn8pAxJ9PYH2shT9ja?dl=0)

Hi,Does the code have an implementation?
