### ISSUE TITLE
Code cannot implement

### ISSUE THREAD

**Issue by wangxiaosong96** [YoungBigBird1985/GCN-MF#2]
I want to quote from this paper，but the results of the operation are quite different from the results of the paper. I want to consultIs the code given complete?
Here are my results:
TEST_MAP: 0.005138896854141778 AUC:0.39171357915088856 nDCG:0.007482806027077702 P@1:0.000870 P@5:0.002087 P@10:0.001739 P@15:0.001681 R@1:0.000870 R@5:0.008841 R@10:0.015797 R@15:0.022899

**Comment by YoungBigBird1985** [comment]
The code should work and repeat the results in our paper.
