### ISSUE TITLE
Is it possible to run this code on my own data？

### ISSUE THREAD

**Issue by YaoXinZhi** [YoungBigBird1985/GCN-MF#3]
Hi，Peng

I want to run the code on my own data, but I noticed that both IMC1 and IMC2 are .mat format files, which is difficult for me to generate. 

So, is it possible to run this code on my own data.

**Comment by YoungBigBird1985** [comment]
Please find out the issue and you will find out some dropout links:
https://www.dropbox.com/request/Qu1UM2I45sFIMJ94WFys

**Comment by YoungBigBird1985** [comment]
https://www.dropbox.com/sh/2uwqlfpqh2tdzi6/AAADqgTrn8pAxJ9PYH2shT9ja?dl=0
